#ifndef _M5NSCONFIG_H
#define _M5NSCONFIG_H

#include <M5StickC.h>
#include "IniFile.h"

struct tConfig {
  char url[64];
  char token[32]; // security token
  int timeZone = 3600; // time zone offset in hours, must be corrected for internatinal use and DST
  int dst = 0; // DST time offset in hours, must be corrected for internatinal use and DST
  int show_mgdl = 0; // 0 = display mg/DL, 1 = diplay mmol/L
  int restart_at_logged_errors = 0; // restart device after particular number of errors in the log (0 = do not restart)
  uint8_t brightness1, brightness2, brightness3;
  char wlanssid[10][32];
  char wlanpass[10][32];

  // password to use for ble client (iphone app) to authenticate towards M5 Stack, immediately after connecting. If not set then M5Stack will generate temporary password
  // if password generated by M5Stack, then the password needs to be send to the client, the very first time
  char blepassword[64];
} ;

void readConfiguration(char *iniFilename, tConfig *cfg);

#endif
